export const discordFeatures = [
  "Real-time messaging using Socket.io",
  "Send attachments as messages using UploadThing",
  "Delete & Edit messages in real time for all users",
  "Create Text, Audio and Video call Channels",
  "1:1 conversation between members",
  "1:1 video calls between members",
  "Member management (Kick, Role change Guest / Moderator)",
  "Unique invite link generation & full working invite system",
  "Infinite loading for messages in batches of 10 (tanstack/query)",
  "Server creation and customization",
  "Beautiful UI using TailwindCSS and ShadcnUI",
  "Full responsivity and mobile UI",
  "Light / Dark mode",
  "Websocket fallback: Polling with alerts",
  "ORM using Prisma",
  "MySQL database using Planetscale",
  "Authentication with Clerk",
];

export const aiSaaSFeatures = [
  "Tailwind design",
  "Tailwind animations and effects",
  "Full responsiveness",
  "Clerk Authentication (Email, Google, 9+ Social Logins)",
  "Client form validation and handling using react-hook-form",
  "Server error handling using react-toast",
  "Image Generation Tool (Open AI)",
  "Video Generation Tool (Replicate AI)",
  "Conversation Generation Tool (Open AI)",
  "Music Generation Tool (Replicate AI)",
  "Page loading state",
  "Stripe monthly subscription",
  "Free tier with API limiting",
  "Folder structure in Next 13 App Router",
];

export const spotifyFeatures = [
  "Song upload",
  "Stripe integration",
  "Tailwind design for sleek UI",
  "Tailwind animations and transition effects",
  "Full responsiveness for all devices",
  "Credential authentication with Supabase",
  "Github authentication integration",
  "File and image upload using Supabase storage",
  "Client form validation and handling using react-hook-form",
  "Server error handling with react-toast",
  "Play song audio",
  "Favorites system",
  "Playlists / Liked songs system",
  "Advanced Player component",
];
